### PR TITLE
Update vendorsetup.sh

### PR DESCRIPTION
**Pull request by ghost**
added Ville to lunch menu.

### CODE REVIEW

**Comment by deadman96385** [comment]
Its not ready yet causes issues with d2

**Comment by ghost** [comment]
Did I do something wrong..adding ville to lunch menu causes issues with d2?

**Comment by ghost** [comment]
I looked at the ville... With all the stuff removed does the ville even
function properly...? All I added was the ville to vendorsetup.sh... Also I
think if you add a folder to vender/liquid named products and house a
liquid.ville.mk and an android.mk in it for building the ville it will
bypass your issue with a full ville tree... I've built a few...

**Comment by ghost** [comment]
Its cool tho we don't have to add anything... I'm fine building the way I've been doin it...

**Comment by ghost** [comment]
Whoa whoa if your talking to me your in the wrong!!! I took nothing from
you or any one else not even sure where you would get that from... I've
been working on this project for all of a day you got the wrong guy..

**Comment by iamronr** [comment]
Tom... show where we copied and we'll gladly credit you homie. You're driven to make a fool of the team, but it really honestly isn't working bro. Honestly... you've moved on to Carbon bro, let TeamLiquid be the past. Just move on dude, your services aren't needed...

I don't know you like that, don't care to know you like that, but it's grown quite annoying that you've moved to another team and still for whatever reason is still here. You're gonna do what you want regardless, but i'm just letting you know bro, you're irrelevant lol. I feel like this is your move to somehow stay relevant lol. TeamLiquid has moved on from what's happened, so you should to bro...

**Comment by ghost** [comment]
Or just delete all the ville stuff and I'll make my own stuff.. Just sayin
what do you have to do with my push to vendor... I have built several of
these roms off my own tree never once forked liquid ville... I'm not trying
to get in the middle here and don't know you ...don't take that the wrong
way... But I would rather use my stuff any way...

**Comment by ghost** [comment]
Let's keep this professional fellas this truly looks bad on both teams....

**Comment by iamronr** [comment]
Yeah I know Ryan did bro, but I also told him to let it go... I may not know all of the facts, personally, I really don't care to know all of the facts. I know the obvious... you're on Carbon, this is LIQUIDSMOOTH. That's the obvious. I know that YOU and RYAN didn't part on the best of terms. Who doesn't know what? 

What I'm getting at is... you're still here.... Why? What reason do you have to be here? 

You claim we copied something, but even before that you were here... Why? You've already formed another team... What's the point? That's what I'm trying to understand...

**Comment by nocoast** [comment]
1. https://github.com/CarbonDev/android_device_htc_ville/commit/eaccc1d3186c846704136ef520d5e943068303fa <my commit
2. https://github.com/LiquidSmooth/android_device_htc_ville/commit/4c7697914e314665ab16ba11f9dc9238b7e74d1e < Same commit with the same msg and all (a day later)
3. https://github.com/CarbonDev/android_device_htc_ville/commit/fcfd09e137f39abcaa50ea703d73eaaa5de4835e <My commit
4. https://github.com/LiquidSmooth/android_device_htc_ville/commit/8959ac57099eba995933384a6777d6a24f945786 <copycat commit (Unicorn butter, PA etc all had no issue crediting me for this.
5. https://github.com/CarbonDev/android_device_htc_ville/commit/3a6bfe6ab23c32b6631416d672292e4cdc612013 < My commit
6. https://github.com/LiquidSmooth/android_device_htc_ville/commit/89ca71fb7ec7951f18e74b8fa677ca0641a2cc1f <copycat commit

**Comment by ghost** [comment]
All that stuff you linked is not even being used.lol the liquid ROM put out
for the ville was built using my device tree which was forked from cm like
every other ROM built by Any one for any device the credit goes to them...

**Comment by ghost** [comment]
My device tree boots fine... And no one is the other of any commits but cm
and me... My device tree, the one that is being used to build for the ville
is on my get hub and has absolutely nothing to do with you or team
liquid... So you are no longer the author of the ville...

**Comment by ghost** [comment]
I can't... I've already asked..

**Comment by nocoast** [comment]
So again i know this is apache, not GPL but since you guys are using your
device tree is there a reason why you guys dont track it in the manifest?
If you have made significant improvements to the tree id love to
cherry-pick your goodies to improve my ville tree...

**Comment by ghost** [comment]
I have no significant improvements its just up to date and works that's
all.. Not saying its better I just like using my own stuff when
possible...hopefully it will be on there soon.. I just started working with
these guys yesterday...

**Pull request closed without merging**
